### PR TITLE
Feature/environment config

### PR DESCRIPTION
**Pull request by danielabar**
Support templated configuration in config files read in by LayerService (servlet/resources...json but could be any text format)

### CODE REVIEW

**Comment by nkronenfeld** [comment]
What is the impetus for this?

If I correctly understand what it's doing, we have been talking about what I think is probably (though not certainly) a better solution - using Tyrpesafe config for our properties; it wouldn't allow substitution, but it would allow overriding very easily, in a way that seems to satisfy the examples I see herein (such as in javadocs), and requires less code and fewer levels of abstraction on our own part.

That being said, I'm not entirely sure I'm reading this PR right, either.. so any explanation would be most useful.

**Comment by cdbethune** [comment]
The config service looks good to me.  I also wanted to offer up a possible alternative: using token replacement via Gradle.  The advantage to using the build system is that the substitution is general - any file that we're touching as part of the build process can have token replacement performed on it.  Sets of paths etc. for each particular deployment can be defined in seperate files, and the correct file can be supplied to the build via argument.  The drawback is that the substitution has to take place at build time, rather than run-time.

I've experimented with this a bit when I was looking at trying to streamline the config process, and have a rough notion of how the build scripts would need to be modified to take advantage of it.  There's an overview of how the filtering works at here: http://mrhaki.blogspot.ca/2010/10/gradle-goodness-copy-files-with.html.  Our case is somewhat different, but the basic replacement strategy is valid.

**Comment by nkronenfeld** [comment]
Could we get one small change - could you please make the substitution syntax the same as typesafe uses, so when we switch over to it, we won't have to change config files?

**Comment by danielabar** [comment]
@nkronenfeld , just want to confirm. Currently, the expected syntax in json files is, for example:

foo.json
```
{
  "service.endpoint" : "[service.endpoint]"
}
```

Then given a properties file such as
```
service.endpoint=http://some.thing
```

ConfigService would return
```
{
  "service.endpoint" : "http://some.thing"
}
```

Is this what I should change foo.json to to make this look more like typesafe-config?

foo.json
```
{
  "service.endpoint" : "${service.endpoint}"
}

**Comment by nkronenfeld** [comment]
yeah, thats all, just a minor syntax difference

**Comment by danielabar** [comment]
The key and template string can be the same or different, shouldn't matter. So foo.json could be

```
{
  "service.endpoint" : "${my.property}"
}
```

And properties file would be

```
my.property=http://some.thing
```

And replacement result would be

```
{
  "service.endpoint" : "http://some.thing"
}
```

**Pull request merged**
